### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by Freyskeyd** [utkarshkukreti/speculate.rs#35]
Hello

I was using speculate for a while now but it seems that no evolutions occurs in the past month.

Does this repository is unmaintained?
Does someone take the lead on it to do improvement?

**Comment by kevlarr** [comment]
Was wondering this too. I *just* found this crate and it looks really neat

**Comment by ghost** [comment]
Since I haven't seen an update to this project in a while I decided to make a new testing framework named [Demonstrate](https://github.com/austinsheep/demonstrate) which takes inspiration from this project.  It has the same functionality as speculate.rs, with some additional features and uses `syn 1.x`.
